"""Removing access codes, adding link between job position and (interview questiosn and competency rubric levels

Revision ID: 2928940d977c
Revises: 8cd1fb1af969
Create Date: 2025-09-22 16:06:09.480043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2928940d977c'
down_revision: Union[str, None] = '8cd1fb1af969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_codes_is_active', table_name='access_codes')
    op.drop_index('ix_access_codes_public_id', table_name='access_codes')
    op.drop_table('access_codes')
    op.add_column('competency_rubric_levels', sa.Column('job_position_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_competency_rubric_levels_job_position_id'), 'competency_rubric_levels', ['job_position_id'], unique=False)
    op.create_foreign_key(None, 'competency_rubric_levels', 'job_positions', ['job_position_id'], ['id'], ondelete='CASCADE')
    op.add_column('interview_questions', sa.Column('job_position_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_interview_questions_job_position_id'), 'interview_questions', ['job_position_id'], unique=False)
    op.create_foreign_key(None, 'interview_questions', 'job_positions', ['job_position_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_questions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_questions_job_position_id'), table_name='interview_questions')
    op.drop_column('interview_questions', 'job_position_id')
    op.drop_constraint(None, 'competency_rubric_levels', type_='foreignkey')
    op.drop_index(op.f('ix_competency_rubric_levels_job_position_id'), table_name='competency_rubric_levels')
    op.drop_column('competency_rubric_levels', 'job_position_id')
    op.create_table('access_codes',
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='access_codes_pkey'),
    sa.UniqueConstraint('code', name='access_codes_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_access_codes_public_id', 'access_codes', ['public_id'], unique=True)
    op.create_index('ix_access_codes_is_active', 'access_codes', ['is_active'], unique=False)
    # ### end Alembic commands ###
