"""added onboaring boolean to employee and removing access-pin from companies

Revision ID: 40a567dfa0c2
Revises: 6c073661aed0
Create Date: 2025-08-28 16:57:21.356841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a567dfa0c2'
down_revision: Union[str, None] = '6c073661aed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_access_pin_key'), 'companies', type_='unique')
    op.drop_column('companies', 'access_pin')
    op.add_column('employees', sa.Column('is_onboarding', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_employees_is_onboarding'), 'employees', ['is_onboarding'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_is_onboarding'), table_name='employees')
    op.drop_column('employees', 'is_onboarding')
    op.add_column('companies', sa.Column('access_pin', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('companies_access_pin_key'), 'companies', ['access_pin'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
