"""creating job type to differentiate between internal and external job

Revision ID: 45ba42961931
Revises: f9405344cf59
Create Date: 2025-09-11 14:03:21.773160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ba42961931'
down_revision: Union[str, None] = 'f9405344cf59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_positions', sa.Column('job_type', sa.Enum('EXTERNAL', 'INTERNAL', name='job_position_type'), nullable=False))
    op.create_index(op.f('ix_job_positions_job_type'), 'job_positions', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_positions_job_type'), table_name='job_positions')
    op.drop_column('job_positions', 'job_type')
    # ### end Alembic commands ###
