"""Initial migration

Revision ID: 4d0a7b4d4732
Revises:
Create Date: 2025-08-26 18:34:37.050760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d0a7b4d4732"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("_phone_number", sa.String(length=20), nullable=False),
        sa.Column("phone_country_code", sa.String(length=8), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidates_email"), "candidates", ["email"], unique=True)
    op.create_index(
        op.f("ix_candidates_public_id"), "candidates", ["public_id"], unique=True
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("access_pin", sa.String(length=12), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_pin"),
    )
    op.create_index(
        op.f("ix_companies_is_active"), "companies", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=True)
    op.create_index(
        op.f("ix_companies_public_id"), "companies", ["public_id"], unique=True
    )
    op.create_table(
        "competencies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competencies_is_active"), "competencies", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_competencies_name"), "competencies", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_competencies_public_id"), "competencies", ["public_id"], unique=True
    )
    op.create_table(
        "competency_rubric_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "BELOW_EXPECTATIONS",
                "MEETS_EXPECTATIONS",
                "ABOVE_AVERAGE",
                "EXCEEDS_EXPECTATIONS",
                "OUTSTANDING",
                name="rubric_score_level_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "label",
            sa.Enum(
                "BELOW",
                "MEETS",
                "ABOVE",
                "EXCEEDS",
                "OUTSTANDING",
                name="rubric_label_enum",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("key_indicators", sa.String(), nullable=True),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"], ["competencies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_competency_rubric_levels_competency_id"),
        "competency_rubric_levels",
        ["competency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competency_rubric_levels_public_id"),
        "competency_rubric_levels",
        ["public_id"],
        unique=True,
    )
    op.create_table(
        "interview_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"], ["competencies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_questions_competency_id"),
        "interview_questions",
        ["competency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_questions_public_id"),
        "interview_questions",
        ["public_id"],
        unique=True,
    )
    op.create_table(
        "job_positions",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAUSED", "COMPLETED", name="job_position_status_enum"),
            server_default=sa.text("'ACTIVE'"),
            nullable=False,
        ),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_positions_company_id"),
        "job_positions",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_positions_public_id"), "job_positions", ["public_id"], unique=True
    )
    op.create_index(
        op.f("ix_job_positions_status"), "job_positions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_job_positions_title"), "job_positions", ["title"], unique=False
    )
    op.create_table(
        "employees",
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("auth0_id", sa.String(length=64), nullable=False),
        sa.Column("job_position_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("_phone_number", sa.String(length=20), nullable=False),
        sa.Column("phone_country_code", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["job_position_id"], ["job_positions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employees_auth0_id"), "employees", ["auth0_id"], unique=True
    )
    op.create_index(
        op.f("ix_employees_company_id"), "employees", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_employees_email"), "employees", ["email"], unique=True)
    op.create_index(
        op.f("ix_employees_job_position_id"),
        "employees",
        ["job_position_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employees_public_id"), "employees", ["public_id"], unique=True
    )
    op.create_table(
        "job_applications",
        sa.Column("applied_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("HIRE", "PENDING", "REJECT", name="job_application_status_enum"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("job_position_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["job_position_id"], ["job_positions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_applications_applied_on"),
        "job_applications",
        ["applied_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_applications_candidate_id"),
        "job_applications",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_applications_job_position_id"),
        "job_applications",
        ["job_position_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_applications_public_id"),
        "job_applications",
        ["public_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_job_applications_status"), "job_applications", ["status"], unique=False
    )
    op.create_table(
        "job_position_competency_mappings",
        sa.Column("job_position_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"], ["competencies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["job_position_id"], ["job_positions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("job_position_id", "competency_id"),
    )
    op.create_table(
        "job_interviews",
        sa.Column("interview_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("interviewer_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["job_applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"], ["competencies.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["interviewer_id"], ["employees.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_interviews_application_id"),
        "job_interviews",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_interviews_competency_id"),
        "job_interviews",
        ["competency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_interviews_interview_datetime"),
        "job_interviews",
        ["interview_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_interviews_interviewer_id"),
        "job_interviews",
        ["interviewer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_interviews_public_id"),
        "job_interviews",
        ["public_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_interviews_public_id"), table_name="job_interviews")
    op.drop_index(op.f("ix_job_interviews_interviewer_id"), table_name="job_interviews")
    op.drop_index(
        op.f("ix_job_interviews_interview_datetime"), table_name="job_interviews"
    )
    op.drop_index(op.f("ix_job_interviews_competency_id"), table_name="job_interviews")
    op.drop_index(op.f("ix_job_interviews_application_id"), table_name="job_interviews")
    op.drop_table("job_interviews")
    op.drop_table("job_position_competency_mappings")
    op.drop_index(op.f("ix_job_applications_status"), table_name="job_applications")
    op.drop_index(op.f("ix_job_applications_public_id"), table_name="job_applications")
    op.drop_index(
        op.f("ix_job_applications_job_position_id"), table_name="job_applications"
    )
    op.drop_index(
        op.f("ix_job_applications_candidate_id"), table_name="job_applications"
    )
    op.drop_index(op.f("ix_job_applications_applied_on"), table_name="job_applications")
    op.drop_table("job_applications")
    op.drop_index(op.f("ix_employees_public_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_job_position_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_email"), table_name="employees")
    op.drop_index(op.f("ix_employees_company_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_auth0_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_job_positions_title"), table_name="job_positions")
    op.drop_index(op.f("ix_job_positions_status"), table_name="job_positions")
    op.drop_index(op.f("ix_job_positions_public_id"), table_name="job_positions")
    op.drop_index(op.f("ix_job_positions_company_id"), table_name="job_positions")
    op.drop_table("job_positions")
    op.drop_index(
        op.f("ix_interview_questions_public_id"), table_name="interview_questions"
    )
    op.drop_index(
        op.f("ix_interview_questions_competency_id"), table_name="interview_questions"
    )
    op.drop_table("interview_questions")
    op.drop_index(
        op.f("ix_competency_rubric_levels_public_id"),
        table_name="competency_rubric_levels",
    )
    op.drop_index(
        op.f("ix_competency_rubric_levels_competency_id"),
        table_name="competency_rubric_levels",
    )
    op.drop_table("competency_rubric_levels")
    op.drop_index(op.f("ix_competencies_public_id"), table_name="competencies")
    op.drop_index(op.f("ix_competencies_name"), table_name="competencies")
    op.drop_index(op.f("ix_competencies_is_active"), table_name="competencies")
    op.drop_table("competencies")
    op.drop_index(op.f("ix_companies_public_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_is_active"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_candidates_public_id"), table_name="candidates")
    op.drop_index(op.f("ix_candidates_email"), table_name="candidates")
    op.drop_table("candidates")
    # ### end Alembic commands ###
