"""removing applied_on cause it's redundant

Revision ID: 5b9fcdc69791
Revises: 7527fa2630d1
Create Date: 2025-09-01 17:22:54.305826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b9fcdc69791'
down_revision: Union[str, None] = '7527fa2630d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_applied_on'), table_name='job_applications')
    op.drop_column('job_applications', 'applied_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('applied_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_job_applications_applied_on'), 'job_applications', ['applied_on'], unique=False)
    # ### end Alembic commands ###
