"""updating roles

Revision ID: 6c073661aed0
Revises: aec276decf09
Create Date: 2025-08-27 16:10:14.031876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c073661aed0"
down_revision: Union[str, None] = "aec276decf09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "role",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.Enum(
            "admin", "recruiter", "interviewer", name="role_enum", native_enum=False
        ),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_employees_role"), "employees", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_role"), table_name="employees")
    op.alter_column(
        "employees",
        "role",
        existing_type=sa.Enum(
            "admin", "recruiter", "interviewer", name="role_enum", native_enum=False
        ),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
