"""removing unused outcome from job interview

Revision ID: 74ce21510aac
Revises: 0b93ba7a2c5e
Create Date: 2025-09-12 23:07:38.306255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ce21510aac'
down_revision: Union[str, None] = '0b93ba7a2c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_interviews', 'outcome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_interviews', sa.Column('outcome', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
