"""new changes adding enum

Revision ID: 7527fa2630d1
Revises: 589280905aa5
Create Date: 2025-09-01 15:30:02.643296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7527fa2630d1'
down_revision: Union[str, None] = '589280905aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_interviews', sa.Column('interview_status', sa.Enum('NOT_SCHEDULED', 'SCHEDULED', 'RESCHEDULED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'FEEDBACK_PENDING', name='interview_status_enum'), server_default=sa.text("'NOT_SCHEDULED'"), nullable=False))
    op.create_index(op.f('ix_job_interviews_interview_status'), 'job_interviews', ['interview_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_interviews_interview_status'), table_name='job_interviews')
    op.drop_column('job_interviews', 'interview_status')
    # ### end Alembic commands ###
