"""removing uncessary label in rubric

Revision ID: 96c0d637a24c
Revises: 45ba42961931
Create Date: 2025-09-11 14:31:38.167309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c0d637a24c'
down_revision: Union[str, None] = '45ba42961931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competency_rubric_levels', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competency_rubric_levels', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
