"""adding description to job positions

Revision ID: 96efd47d7d18
Revises: dfeaccf3b45e
Create Date: 2025-08-30 22:48:10.255570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96efd47d7d18'
down_revision: Union[str, None] = 'dfeaccf3b45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_positions', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_positions', 'description')
    # ### end Alembic commands ###
