"""adding interview status to job interview

Revision ID: 9f297feaec16
Revises: a0bcba49d2ac
Create Date: 2025-09-01 15:21:05.380948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f297feaec16'
down_revision: Union[str, None] = 'a0bcba49d2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_interviews', sa.Column('status', sa.Enum('NOT_SCHEDULED', 'SCHEDULED', 'RESCHEDULED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'FEEDBACK_PENDING', name='job_position_status_enum'), server_default=sa.text("'NOT_SCHEDULED'"), nullable=False))
    op.create_index(op.f('ix_job_interviews_status'), 'job_interviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_interviews_status'), table_name='job_interviews')
    op.drop_column('job_interviews', 'status')
    # ### end Alembic commands ###
