"""adding score to job_interviews

Revision ID: a0bcba49d2ac
Revises: 96efd47d7d18
Create Date: 2025-09-01 14:36:43.045531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bcba49d2ac'
down_revision: Union[str, None] = '96efd47d7d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_interviews', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_interviews', 'score')
    # ### end Alembic commands ###
