"""new employee model with username and password

Revision ID: a6ddc77a89bc
Revises: b6a4b39c6291
Create Date: 2025-09-07 15:12:02.561045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ddc77a89bc'
down_revision: Union[str, None] = 'b6a4b39c6291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_column('candidates', 'full_name')
    op.add_column('employees', sa.Column('username', sa.String(length=32), nullable=True))
    op.add_column('employees', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('employees', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index('ix_employees_auth0_id', table_name='employees')
    op.drop_index('ix_employees_is_onboarding', table_name='employees')
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.drop_column('employees', 'is_onboarding')
    op.drop_column('employees', 'auth0_id')
    op.drop_column('employees', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('auth0_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('is_onboarding', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.create_index('ix_employees_is_onboarding', 'employees', ['is_onboarding'], unique=False)
    op.create_index('ix_employees_auth0_id', 'employees', ['auth0_id'], unique=True)
    op.alter_column('employees', 'email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'password')
    op.drop_column('employees', 'username')
    op.add_column('candidates', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('candidates', 'email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('candidates', 'last_name')
    op.drop_column('candidates', 'first_name')
    # ### end Alembic commands ###
