"""updating phone number representation

Revision ID: c61c1cc1b5d8
Revises: 40a567dfa0c2
Create Date: 2025-08-29 00:02:15.781738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61c1cc1b5d8'
down_revision: Union[str, None] = '40a567dfa0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('phone_number_raw', sa.String(length=20), nullable=False))
    op.drop_column('candidates', '_phone_number')
    op.add_column('employees', sa.Column('phone_number_raw', sa.String(length=20), nullable=False))
    op.drop_column('employees', '_phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('employees', 'phone_number_raw')
    op.add_column('candidates', sa.Column('_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('candidates', 'phone_number_raw')
    # ### end Alembic commands ###
