"""changed a few things to be nullable True

Revision ID: dd030c2ecba0
Revises: 74ce21510aac
Create Date: 2025-09-14 14:52:44.676039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd030c2ecba0'
down_revision: Union[str, None] = '74ce21510aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_interviews', 'interview_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('job_interviews', 'interviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_interviews', 'interviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_interviews', 'interview_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
