"""removing access codes

Revision ID: f9405344cf59
Revises: 56b5ade0b5e6
Create Date: 2025-09-08 23:36:50.921090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9405344cf59'
down_revision: Union[str, None] = '56b5ade0b5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_codes_company_id', table_name='access_codes')
    op.drop_constraint('access_codes_company_id_fkey', 'access_codes', type_='foreignkey')
    op.drop_column('access_codes', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_codes', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('access_codes_company_id_fkey', 'access_codes', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_access_codes_company_id', 'access_codes', ['company_id'], unique=False)
    # ### end Alembic commands ###
